# Site settings
title: OSS Gateオンボーディング
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  OSS Gateオンボーディングはより深くOSS開発に取り組み始めたい人を支援する取り組みです。

  OSS GateワークショップではOSS開発に取り組んだことがない人が取り組めるようになることを支援する取り組みですが、OSS Gateオンボーディングはその次のステップを支援する取り組みです。
baseurl: "/on-boarding" # the subpath of your site, e.g. /blog
url: "https://oss-gate.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  oss-gate

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options:
    - FOOTNOTES
    - GITHUB_PRE_LANG
  extensions:
    - autolink
    - table
    - strikethrough

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
